# Generated by Django 4.2.5 on 2023-11-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0007_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_number',
        ),
    ]
